### PR TITLE
Allow regenerating the Class file to expand available Mime Types.

### PR DESCRIPTION
**Pull request by thebeline**
This adds a template and a script that together allow re-generating the class based on the current Mime Types listed at `http://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types`.

This also makes two functions public, and adds a function for `finfoType`, as a fall-back is we don't have the Mime Type in out list.

### CODE REVIEW

**Comment by katzien** [comment]
Hi @thebeline! Thanks for the PR.

There are a few things that make me unwilling to accept your changes:
- unit tests are broken (they have not been updated)
- putting the @ sign in front of functions to silence errors is bad practice
- I don't like the idea of dynamically generating the source code - it makes it untestable and really hard to debug

I do agree though that the list could do with updating to match the list from apache. I'll do that shortly :)

**Comment by thebeline** [comment]
Fair enough.

- Unit tests are broken (I didn't break them, so, I am confused why that is a mark against the branch).
- I am well aware that the `@` symbol is contraindicated, however, as we are accessing files with unknown permissions, and a url that may have issues, we silence it and do the error handling ourselves, that's not a product of bad form, that was a choice.
- Eh.  I mean, I didn't make unit tests for you, but I am certain I could have if I had cared to.  In the initialization of the test environment I would have it execute the re-builder to form the class, and we would have unit tests as you usually do.  It's really not all that odd.

All of that said (thumbs, and all that), you don't have to do anything, because, if you noticed in the Diff, I already did...  ;-)

**Comment by thebeline** [comment]
Ah, I see you already accounted for the list this evening.

Side Note: Besides dependencies needed for unit testing, are there any actual features in this that require anything above 5.4?

**Comment by katzien** [comment]
The 1.x branch works from 5.3 not 5.4. The only difference between 1.x and 2.x, aside from the test dependencies, is the short array syntax :) Functionally and usage-wise they're exactly the same.

**Comment by thebeline** [comment]
Yeah, the only reason I said 5.4 was because the short syntax was introduced in 5.4, which means (aside from test dependencies) the library is feature compat with 5.3+, or, at the very least, with it it is compat with 5.4+.  Just not sure why you would limit the use-cases with requiring 5.6+ when that is only needed unit tests.  Shouldn't that be covered if someone were to activate composer dev, which would include the testing utils, and they would specify their required PHP?

**Comment by katzien** [comment]
The main reason for this split of versions is phpunit - the old (now unsupported) 4.* release supports 5.3 - 5.6, 5.* supports 5.6-7.1 and the latest 6.* which I haven't switched this lib to yet supports 7.0-7.1 only.

So basically I need different composer.json files, hence the need for different branches. 

I don't want to use 4.* phpunit just because the library works from 5.3 onwards. I want the latest version of this library to use the latest phpunit, and that unfortunately means versioning (even if in this case there are no differences feature-wise). 

There may be better ways to do this - I'm by no means an expert so this is my first go at it.

**Comment by thebeline** [comment]
If I understand it correctly, by having the newer PHPUnit in `require-dev`, it will check it's required PHP version when, and only if you load composer with the dev directive, or whatever, which means that library it's self will define the requirement.

I think you are safe to have the correct non-dev PHP version in your Composer file, and the require (when doing tests, etc) will handle the rest.  It may be necessary to have a PHPUnit directive to prevent testing against older PHP versions.  However that would mean you would no longer test against older versions.

I don't know, it seems a shame to prevent older versions from using this when in-fact it is supported on their version... :-/  Maybe you should bite the bullet and use the 4.* PHPUnit?  I mean, I would guess that it is a matter of efficiency, I doubt the behavior is that different.  Also, considering the relatively low complexity of this project, and the limited PHPUnit Tests required, it doesn't strike me as a real need.

If you open up the require, you increase the coverage area of developers who can use this.  I would think you would want to make more lives easier, rather than stick to bleeding edge for the sake of it.

My 10 cents.  We are using this on php 5.4 with no issues, but I was unable to track it with composer because of the requirement.  Seems a shame.

**Pull request closed without merging**
